/**
 * Core types for Delta-Curator
 * Shared across all packages
 */

/**
 * Event header - metadata about an event
 * Per AGENT_BRIEF.md section 4: Identity & Ordering
 */
export interface EventHeader {
  // Identity
  event_type: string; // e.g., "item_observed", "item_assessed", "item_decided"
  event_version: string; // e.g., "1.0"

  // Hashing
  event_id: string; // SHA256(type + source_item_id + semantic_core(payload))
  payload_hash: string; // SHA256(canonical_json(payload))
  hash_alg: 'dc-v1-semcore'; // Algorithm version

  // Tracing & Source
  trace_id: string; // Generated by Runner per batch
  source_id: string; // Identifies the source plugin
  source_item_id: string; // Unique per source

  // Ordering
  candidate_seq: number; // Runner-assigned sequence number per stage
  commit_id?: string; // Set after commit succeeds

  // Audit
  observed_at: string; // ISO 8601 timestamp (excluded from event_id)
}

/**
 * Complete event with payload
 */
export interface Event<TPayload = unknown> extends EventHeader {
  payload: TPayload;
}

/**
 * Source state - opaque JSON state maintained by source plugin
 */
export type SourceState = Record<string, unknown>;

/**
 * Raw document as observed from source
 */
export interface RawDocObserved {
  source_item_id: string;
  observed_at: string; // ISO 8601
  payload: unknown; // Arbitrary JSON
}

/**
 * Mutations to apply to read models
 */
export interface ViewMutation {
  view: string; // Table name: facet_index, fingerprint_index, hold_index, curated_docs
  operation: 'insert' | 'update' | 'delete';
  key: unknown; // Primary key
  data?: unknown; // Data for insert/update
}

/**
 * Artifact reference
 */
export interface ArtifactRef {
  key: string; // Filename-safe identifier
  sha256: string; // Integrity check
}

/**
 * Commit request - assembled before calling Committer.commit()
 * All fields are immutable and precomputed
 */
export interface CommitRequest {
  commitKey: string; // Deterministic hash of (sourceId, oldState, itemIds)
  traceId: string; // Batch identifier
  sourceId: string; // Source plugin id
  oldState: SourceState; // Previous source state
  newState: SourceState; // New source state (proposed)
  events: Event<unknown>[]; // Events to persist
  mutations: ViewMutation[]; // Read model mutations
  artifacts?: Record<string, ArtifactRef>; // Optional artifacts to persist
}

/**
 * Commit response
 */
export interface CommitResponse {
  commitId: string; // Unique identifier for this commit
}

/**
 * Candidate document - immutable envelope for an item being processed
 */
export interface CandidateDoc {
  trace_id: string;
  source_item_id: string;
  candidate_seq: number; // Stage sequence
  observed_at: string; // ISO 8601
  payload: unknown; // Arbitrary JSON
}

/**
 * Read model snapshot
 */
export interface BaseView {
  viewName: string;
  state: Record<string, unknown>; // Snapshot of view state
}

/**
 * Result from comparator plugin
 */
export interface ComparisonResult {
  source_item_id: string;
  novelty: 'novel' | 'duplicate' | 'similar';
  confidence: number; // 0.0-1.0
  rationale?: string;
}

/**
 * Analysis output from comparator, input to decider
 */
export interface CandidateAnalysis {
  candidate: CandidateDoc;
  comparison: ComparisonResult;
  baseViews: BaseView[];
}

/**
 * Decision from decider plugin
 */
export interface DecisionResult {
  source_item_id: string;
  decision: 'append' | 'merge' | 'hold' | 'reject';
  reason?: string;
  targetId?: string; // For merge decisions: which doc to merge into
}

/**
 * Merge result from merger plugin
 */
export interface MergeResult {
  merged: CandidateDoc;
  artifacts?: Record<string, Buffer>;
}

/**
 * Resolved view snapshot
 */
export interface ResolveView {
  name: string;
  snapshot: unknown;
}
